[package]
name = "lipschitz-rs"
version = "0.1.0"
authors = ["Ethan Spurlock <ethan@spurlock.io>"]
edition = "2018"

[dependencies]
tree-sitter = "0.3.10"
serde_json = "1.0"
tree-sitter-javascript = { git = "https://github.com/racer161/tree-sitter-javascript" }

[build-dependencies]
cc = "1.0"
